hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Cuenta una Historia
description: Crea una página web que narre una historia, broma o poema.
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: ''
technologies: html/css
site_areas: codeclub, webdev
steps:
- title: Introducción
- title: Decide que quieres contar
- title: Edita tu historia
- title: 'Desafío: Haz algunos cambios'
- title: Contando tu historia
- title: 'Desafío: ¡Continuamos!'
